### ISSUE TITLE
Typo in if expression

### ISSUE THREAD

**Issue by 4LT** [JosiahJack/Keep#7]
https://github.com/JosiahJack/Keep/blob/fcdd969dd51204a8efce45a1e51bd2876fdfe04a/keepsrc/mon_hknight.qc#L280

self.classtype == self.classtype == CT_MONSABERENFORCER

evaluates to

TRUE == CT_MONSABERENFORCER

**Comment by JosiahJack** [comment]
Fixed by https://github.com/JosiahJack/Keep/commit/14a422e0fe0c4dfbce935b400705da4c472f3ad1
