### ISSUE TITLE
Progs Crash @dlord_shot

### ISSUE THREAD

**Issue by 4LT** [JosiahJack/Keep#9]
![image](https://github.com/JosiahJack/Keep/assets/3385021/38267678-e8c0-4555-92a2-9f7c481ab38a)

https://github.com/JosiahJack/Keep/blob/fcdd969dd51204a8efce45a1e51bd2876fdfe04a/keepsrc/mon_hknight.qc#L262

dlord_shot calls hknight_shot, which may return *world*

dlord_shot proceeds to assign classname to returned *world*

**Comment by JosiahJack** [comment]
Fixed in https://github.com/JosiahJack/Keep/commit/e803b1b6e2f002312b0093f3ce41c3cde8eb33f9
